# 넘파이 복습

In [1]:
import numpy as np
import torch
# 1차원
t1 = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t1)
print(t1.ndim) # 차원
print(t1.shape) # 모양

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)


In [2]:
# 2차원
t2 = np.array([
    [1.,2.,3.],
    [4.,5.,6.],
    [7.,8.,9.],
    [10.,11.,12.]
])
print(t2)
print(t2.ndim) # 차원
print(t2.shape) # 모양

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


# 파이토치 연산

### pytorch tensor

In [3]:
# 1차원
T1 = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(T1)
print(T1.dim()) # dim()
print(T1.shape) # shape
print(T1.size()) # size()
print(T1[0],T1[1],T1[-1])
print(T1[2:5], T1[4:-1])
print(T1[:2], T1[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [4]:
# 2차원
T2 = torch.FloatTensor([
    [1.,2.,3.],
    [4.,5.,6.],
    [7.,8.,9.],
    [10.,11.,12.]
])
print(T2)
print(T2.dim()) 
print(T2.shape) 
print(T2.size()) 
print(T2[:,1])
print(T2[:,1].size())
print(T2[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### broadcasting : 다른 사이즈의 행렬도 사이즈를 맞춰서 계산

In [5]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [6]:
# vector + scalar
m3 = torch.FloatTensor([[3,3]])
m4 = torch.FloatTensor([3]) # 3 -> [[3,3]]으로 변환
print(m3 + m4)

tensor([[6., 6.]])


In [7]:
# 2*1 vector + 1*2 vector
m5 = torch.FloatTensor([[1,2]])
m6 = torch.FloatTensor([[3],[4]])
print(m5 + m6)

tensor([[4., 5.],
        [5., 6.]])


In [8]:
# broadcasting 때문에 원래 오류가 발생해야 하는 연산에서 
# 오류를 발견하지 못하고 프로그램이 진행된다는 단점이 있음 -> 이점 유의!!

### multiplication vs matrix multiplication

In [9]:
# element 곱
s1 = torch.FloatTensor([[1,2],[3,4]])
s2 = torch.FloatTensor([[1], [2]])
print(s1.mul(s2))

tensor([[1., 2.],
        [6., 8.]])


In [10]:
# 행렬 곱
s3 = torch.FloatTensor([[1,2],[3,4]])
s4 = torch.FloatTensor([[1], [2]])
print(s3.matmul(s4))

tensor([[ 5.],
        [11.]])


### mean

In [11]:
# 편균 계산
d = torch.FloatTensor([1,2])
print(d.mean()) # mean()

tensor(1.5000)


In [12]:
# mean() 함수는 int 형에서 사용할 수 없음
d = torch.LongTensor([1,2])
try:
    print(d.mean())
except Exception as exc:
    print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [13]:
d = torch.FloatTensor([[1,2],[3,4]])
print(d)
print(d.mean()) # 전체 4개의 element에 대해서
print(d.mean(dim=0)) # 1과3, 2와4
print(d.mean(dim=1)) # 1과2, 3과4
print(d.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### sum

In [14]:
d = torch.FloatTensor([[1,2],[3,4]])
print(d)
print(d.sum()) # 전체 4개의 element에 대해서
print(d.sum(dim=0)) # 1과3, 2와4
print(d.sum(dim=1)) # 1과2, 3과4
print(d.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### max and argmax

In [15]:
# max는 큰 값을, argmax는 큰 값의 인덱스 값을 반환
d = torch.FloatTensor([[1,2],[3,4]])
print(d)

tensor([[1., 2.],
        [3., 4.]])


In [16]:
print(d.max())

tensor(4.)


In [17]:
print(d.max(dim=0))
print(d.max(dim=0)[0]) # max
print(d.max(dim=0)[1]) # argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])


In [18]:
print(d.max(dim=1))
print(d.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### view (reshape) 굉장히 중요하다!!

In [19]:
t = np.array([
    [[0,1,2],[3,4,5]],
    [[6,7,8],[9,10,11]]
])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [20]:
print(ft.view(-1,3))
print(ft.view(-1,1,3))
print(ft.view(-1,1,3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### squeeze 차원이 1인 경우 차원을 없애줌 ex) (3,1) -> (3)

In [21]:
ft = torch.FloatTensor([[0],[1],[2]])
# ft = torch.FloatTensor([
#     [1,2,3],[4,5,6]
# ])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
# squeeze(dim=0) -> 첫번째
print(ft.squeeze(dim=0)) # 0번째 dim = 3, 똑같음 -> 변화가 없음
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3])


### unsqueeze

In [38]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [39]:
# 0번째 차원에 1을 넣어 확장
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [41]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [44]:
# 1번째 차원에 1을 넣어 확장
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [46]:
# 마지막 번째 차원에 1을 넣어 확장 -> dim = 1
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### type casting

In [47]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [48]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [49]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [50]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### concatenate (사슬) -> 이어 붙이기

In [55]:
x = torch.FloatTensor([[1,2],[3,4]]) # 2*2
y = torch.FloatTensor([[5,6],[7,8]]) # 2*2

print(torch. cat([x,y], dim=0)) 
# dim 0에 대해서 이어붙이기 (세로로 길어짐) -> 4*2

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [56]:
print(torch.cat([x,y], dim=1)) 
# dim 1에 대해서 이어붙이기 (가로로 길어짐) -> 2*4

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### stacking -> concatenation을 조금 더 편리하게 사용
> stack(텐서 리스트, dim) -> 리스트 안의 텐서들을 dim에 대하여 합쳐라

In [65]:
x = torch.FloatTensor([1,4]) 
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [66]:
print(torch.stack([x,y,z], dim =1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [71]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
# x.unsqueeze(0) -> (1,2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### ones & zeros

In [73]:
x = torch.FloatTensor([[1,2,3],[2,1,0]])
print(x)

tensor([[1., 2., 3.],
        [2., 1., 0.]])


In [74]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [75]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### in-place operation

In [80]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x) # 다시 출력하면 원래대로 돌아옴

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [81]:
print(x.mul_(2.))
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
